#!/usr/bin/env bash
# Configure Nginx with a custom HTTP response header

apt-get update
apt-get install -y nginx

HOSTNAME=$(hostname)

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    add_header X-Served-By \$hostname;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

systemctl restart nginx
