#!/usr/bin/env bash
# Install and configure HAProxy

apt-get update -y
apt-get install -y haproxy

cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 35.175.145.236:80 check
    server web02 44.204.75.77:80 check
EOF

systemctl enable haproxy
systemctl restart haproxy
