#!/usr/bin/env bash
# Installs and configures Nginx to listen on port 80 and serve "Holberton School".

apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start
