#!/usr/bin/env bash
# Configure Nginx custom 404 page

apt-get -y update
apt-get -y install nginx

cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }
}
EOF

echo "Ceci n'est pas une page" > /var/www/html/404.html

nginx -t
systemctl reload nginx
